<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsCoreModule>true</IsCoreModule>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\F.Configurator.Expressions\F.Configurator.Expressions.csproj" />
    <ProjectReference Include="..\F.Configurator.StepResult\F.Configurator.StepResult.csproj" />
  </ItemGroup>
</Project>
